schema_version = 3

[runtime]
mode = "normal"
compression_threshold_bytes = 0

[compressor_plugins]
compressors = ["zfp"]
library_path = "../../../build/obj/device/compress/libcompress"

[normal.sendrecv.default]
compressor = "zfp"

[normal.sendrecv.default.config]
rate = 8
