[runtime]
mode = "normal"
compression_threshold_bytes = 0

[compressor_plugins]
compressors = ["sdp4bit", "zfp"]
library_path = "../../../build/obj/coccl-extend/compressor_plugin/libcompress"

[normal.all_to_all.default]
compressor = "sdp4bit"

[normal.all_to_all.default.config]
groupCount = 2048
quantBits = 4
quantType = "Symmetric"

[normal.all_gather.default]
compressor = "sdp4bit"

[normal.all_gather.default.config]
groupCount = 2048
quantBits = 4
quantType = "Symmetric"

[normal.all_reduce.default]
compressor = "sdp4bit"

[normal.all_reduce.default.config]
groupCount = 128
quantBits = 4
quantType = "Symmetric"
hadamard = false

[normal.all_reduce.intra]
compressor = "sdp4bit"

[normal.all_reduce.intra.config]
groupCount = 128
quantBits = 4
quantType = "Symmetric"
hadamard = true
pipelineSize = 1

[normal.all_reduce.inter]
compressor = "sdp4bit"

[normal.all_reduce.inter.config]
groupCount = 128
quantBits = 4
quantType = "Symmetric"
hadamard = true
pipelineSize = 1

[normal.reduce_scatter.default]
compressor = "sdp4bit"

[normal.reduce_scatter.default.config]
groupCount = 128
quantBits = 4
quantType = "Symmetric"
hadamard = true

[normal.reduce_scatter.intra]
compressor = "sdp4bit"

[normal.reduce_scatter.intra.config]
groupCount = 128
quantBits = 4
quantType = "Symmetric"
hadamard = true
pipelineSize = 1

[normal.reduce_scatter.inter]
compressor = "sdp4bit"

[normal.reduce_scatter.inter.config]
groupCount = 128
quantBits = 4
quantType = "Symmetric"
hadamard = true
pipelineSize = 1
