[runtime]
mode = "normal"
compression_threshold_bytes = 17179869184

[compressor_plugins]
compressors = ["sdp4bit", "zfp"]
library_path = "../../../build/obj/coccl-extend/compressor_plugin/libcompress"

[normal.all_to_all.default]
compressor = "sdp4bit"

[normal.all_to_all.default.config]
groupCount = 2048
quantBits = 4
quantType = "Symmetric"
